### ISSUE TITLE
Make doesn't work

### ISSUE THREAD

**Issue by luky1984** [apertium/apertium-html-tools#348]
Running make command in apertium html tools doesn't work, it makes JSONDecodeError error:

> json.decoder.JSONDecodeError: Expecting value: line 2 column 19
at parser.locale = json.loads(''.join(open(json_path).readlines()))

this worked as fix probably:

`parser.locale = json.loads(json.dumps(''.join(open(json_path).readlines())))
`
and also all places where is json.loads, but then there is another problem:

> Traceback (most recent call last):
>   File "./tools/localise-html.py", line 128, in <module>
>     run(args.template, args.localisations, args.output, args.config, args.fallback)
>   File "./tools/localise-html.py", line 109, in run
>     **parser.alpha2name = parser.locale['alpha2']**
> **TypeError: string indices must be integers**

if i change the problematic line to
parser.alpha2name = ''

there is another error:

> Traceback (most recent call last):
>   File "./tools/localise-html.py", line 128, in <module>
>     run(args.template, args.localisations, args.output, args.config, args.fallback)
>   File "./tools/localise-html.py", line 113, in run
>     parser.feed(''.join(open(html_path).readlines()))
>   File "/usr/lib/python3.6/html/parser.py", line 111, in feed
>     self.goahead(0)
>   File "/usr/lib/python3.6/html/parser.py", line 171, in goahead
>     k = self.parse_starttag(i)
>   File "/usr/lib/python3.6/html/parser.py", line 345, in parse_starttag
>     self.handle_starttag(tag, attrs)
>   File "./tools/localise-html.py", line 41, in handle_starttag
**>     text = self.locale[attr[1]]
> TypeError: string indices must be integers**

full output of first error below, btw yes i ran

pip install -r requirements-prod.txt
pip install -r requirements-dev.txt

and still it says csscompressor not installed but that's a minor problem here.

> make

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'jsmin'
> 
> Skipping JS minification since jsmin not installed.
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'csscompressor'
> 
> Skipping CSS minification since csscompressor not installed.
> 
> ./tools/localise-html.py -c config.conf build/index.localiseme.html build/strings/eng.json build/index.eng.html.tmp
> Traceback (most recent call last):
>   File "./tools/localise-html.py", line 128, in <module>
>     run(args.template, args.localisations, args.output, args.config, args.fallback)
>   File "./tools/localise-html.py", line 106, in run
>     parser.locale = json.loads(''.join(open(json_path).readlines()))
>   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 2 column 19 (char 20)
> Makefile:142: recipe for target 'build/index.eng.html' failed
> make: *** [build/index.eng.html] Error 1

**Comment by luky1984** [comment]
Hm... i was messing with this couple of hours but it turned out that problem was that the APY url in config was ending with /. It must end without /

APY_URL = something (must not end with /)
